apiVersion: v1
kind: Service
metadata:
  name: {{ include "booth-pipeline.fullname" . }}
  labels:
    {{- include "booth-pipeline.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "booth-pipeline.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
